IP = "localhost"
PORT = 3306
USER = "root"
PWD = "123456"
NAME = "TreeHole"
SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{USER}:{PWD}@{IP}:{PORT}/{NAME}?charset=utf8mb4"
MAIL_SERVER = ""
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_DEFAULT_SENDER = ''
MAIL_USERNAME = ""
MAIL_PASSWORD = ""
