"""empty message

Revision ID: ea02eec0bb35
Revises: 
Create Date: 2024-02-28 16:39:57.241312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea02eec0bb35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_email_verify_code',
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('isused', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('db_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('db_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nick', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nick')
    )
    op.create_table('db_account_fingerprint',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gen_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('db_logger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exec_time', sa.DateTime(), nullable=True),
    sa.Column('exec_id', sa.Integer(), nullable=False),
    sa.Column('exec_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exec_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_post_articles',
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(length=65536), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('view', sa.Integer(), nullable=False),
    sa.Column('like', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['db_user.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['db_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('db_comments',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('father_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['db_post_articles.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['db_user.id'], ),
    sa.ForeignKeyConstraint(['father_comment_id'], ['db_comments.comment_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('db_like_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['db_post_articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_like_records')
    op.drop_table('db_comments')
    op.drop_table('db_post_articles')
    op.drop_table('db_logger')
    op.drop_table('db_account_fingerprint')
    op.drop_table('db_user')
    op.drop_table('db_type')
    op.drop_table('db_email_verify_code')
    # ### end Alembic commands ###
